### ISSUE TITLE
Unnecessary await return

### ISSUE THREAD

**Issue by mkupiniak** [zygos/mailerlite-api-v2-node#11]
I see loads of code with `return await` like in this example from `account.ts`:
```ts
return {
    async getAccountRaw(): Promise<AccountWrap> {
      return await client.get('me')
    },

    async getAccount() {
      const { account } = await this.getAccountRaw()
      return account
    },

    async getMe() {
      return await this.getAccount()
    },
  }
```
since `client` is already a Promise you could do just:
```ts
return {
   getAccountRaw(): Promise<AccountWrap> {
      return client.get('me')
    },
...
}
```

**Comment by zygos** [comment]
Yes, this code has been changed just a few weeks ago to have an explicit `return await` in order to enforce `standard-with-typescript` linter preset.

While I personally agree with you and I'd only await a Promise in a try-catch block, I don't see much of a reason to deviate from a picked linting ruleset in an open source project.

More info on rules:
https://github.com/typescript-eslint/typescript-eslint/blob/v4.5.0/packages/eslint-plugin/docs/rules/promise-function-async.md
https://github.com/typescript-eslint/typescript-eslint/blob/v4.5.0/packages/eslint-plugin/docs/rules/return-await.md
